# version format
version: 1.6.{build}.0

# branches to build
branches:
  # whitelist
  only:
    - master
    - develop

# Do not build on tags (GitHub only)
skip_tags: true

# environment variables
environment:
  SignTool: C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\Bin\signtool.exe
  KeyFile: C:\projects\logviewer\logviewer.pfx
  LogviewerSnkPath: C:\projects\logviewer\logviewer.snk
  # this is how to set encrypted variable. Go to "Encrypt data" page in account menu to encrypt data.
  CertPassword:
    secure: QDWBD+3IIAYVFCfHFY7YCw==
  PfxUri:
    secure: XEuoeeDga1uv8WAMxwl2rrxa5zv7b390mRGildlBEijlX5KIfhlLW1TPMdfBNSN22EpuRk8gkoYo8TyfD0qNX3eujjyMlwKYQeVwNcjrbQc=
  SnkUri:
    secure: 96Uy0sDkAp6sTkaD5MptudqaMXrjJkaBQhghxNHvaP9vHbUOcF1R9h9k3LXG6ZnwWkZOmP1fCRP5m2Bclrbc22uOBlleZWaxVycTis9Jb4QCSI2FFddeTQAxehQypUsI

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

install:
    - ps: if($env:PfxUri) { Start-FileDownload $env:PfxUri -FileName $env:KeyFile }
    - ps: if($env:SnkUri) { Start-FileDownload $env:SnkUri -FileName $env:LogviewerSnkPath }
    - cmd: nuget restore

platform: Any CPU

configuration: Release

before_build:
   -cmd: msbuild WiX.msbuild /p:Version=%APPVEYOR_BUILD_VERSION%

build:
    project: logviewer.sln

after_build:
    -cmd: msbuild logviewer.engine\logviewer.engine.csproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Rebuild /p:Configuration=%CONFIGURATION%;Platform=AnyCPU;SnkPath=%LogviewerSnkPath%

test:
  assemblies:
    - logviewer.tests.dll

after_test:
    -cmd: nuget pack logviewer.engine\logviewer.engine.nuspec -BasePath logviewer.engine -OutputDirectory logviewer.engine\bin\%CONFIGURATION% -Version %APPVEYOR_BUILD_VERSION%

artifacts:
  - path: logviewer.engine\bin\$(configuration)\*.nupkg
  - path: logviewer.install.bootstrap\bin\$(configuration)\*.exe

