// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace logviewer.tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SpecOpenLogFileFeature : Xunit.IClassFixture<SpecOpenLogFileFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "SpecOpenLogFile.feature"
#line hidden
        
        public SpecOpenLogFileFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SpecOpenLogFile", "\tTesting opening log file and parsing it", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(SpecOpenLogFileFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="No filtering case")]
        [Xunit.TraitAttribute("FeatureTitle", "SpecOpenLogFile")]
        [Xunit.TraitAttribute("Description", "No filtering case")]
        [Xunit.TraitAttribute("Category", "mainmodel")]
        public virtual void NoFilteringCase()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No filtering case", new string[] {
                        "mainmodel"});
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given("I have file \"test.log\" on disk", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
  testRunner.And("The file contains 2 messages with levels \"INFO\" and \"ERROR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.When("I press open with default filtering parameters", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
   testRunner.And("wait 6 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.Then("the number of shown messages should be 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="All messages filtered by level")]
        [Xunit.TraitAttribute("FeatureTitle", "SpecOpenLogFile")]
        [Xunit.TraitAttribute("Description", "All messages filtered by level")]
        [Xunit.TraitAttribute("Category", "mainmodel")]
        public virtual void AllMessagesFilteredByLevel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All messages filtered by level", new string[] {
                        "mainmodel"});
#line 13
this.ScenarioSetup(scenarioInfo);
#line 14
 testRunner.Given("I have file \"test.log\" on disk", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 15
   testRunner.And("The file contains 2 messages with levels \"INFO\" and \"ERROR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
 testRunner.When("I press open with min level \"Fatal\" and max level \"Fatal\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 17
   testRunner.And("wait 6 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.Then("the number of shown messages should be 0", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Some messages filtered by level min equal max")]
        [Xunit.TraitAttribute("FeatureTitle", "SpecOpenLogFile")]
        [Xunit.TraitAttribute("Description", "Some messages filtered by level min equal max")]
        [Xunit.TraitAttribute("Category", "mainmodel")]
        public virtual void SomeMessagesFilteredByLevelMinEqualMax()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Some messages filtered by level min equal max", new string[] {
                        "mainmodel"});
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
 testRunner.Given("I have file \"test.log\" on disk", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 23
   testRunner.And("The file contains 2 messages with levels \"INFO\" and \"ERROR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 24
 testRunner.When("I press open with min level \"Info\" and max level \"Info\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 25
   testRunner.And("wait 6 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.Then("the number of shown messages should be 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Some messages filtered by level min less max")]
        [Xunit.TraitAttribute("FeatureTitle", "SpecOpenLogFile")]
        [Xunit.TraitAttribute("Description", "Some messages filtered by level min less max")]
        [Xunit.TraitAttribute("Category", "mainmodel")]
        public virtual void SomeMessagesFilteredByLevelMinLessMax()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Some messages filtered by level min less max", new string[] {
                        "mainmodel"});
#line 29
this.ScenarioSetup(scenarioInfo);
#line 30
 testRunner.Given("I have file \"test.log\" on disk", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 31
   testRunner.And("The file contains 2 messages with levels \"INFO\" and \"ERROR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 32
 testRunner.When("I press open with min level \"Trace\" and max level \"Info\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 33
   testRunner.And("wait 6 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.Then("the number of shown messages should be 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Some messages filtered by level min greater max")]
        [Xunit.TraitAttribute("FeatureTitle", "SpecOpenLogFile")]
        [Xunit.TraitAttribute("Description", "Some messages filtered by level min greater max")]
        [Xunit.TraitAttribute("Category", "mainmodel")]
        public virtual void SomeMessagesFilteredByLevelMinGreaterMax()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Some messages filtered by level min greater max", new string[] {
                        "mainmodel"});
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
 testRunner.Given("I have file \"test.log\" on disk", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 39
   testRunner.And("The file contains 2 messages with levels \"INFO\" and \"ERROR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.When("I press open with min level \"Info\" and max level \"Warn\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 41
   testRunner.And("wait 6 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.Then("the number of shown messages should be 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="No filtering case. reload")]
        [Xunit.TraitAttribute("FeatureTitle", "SpecOpenLogFile")]
        [Xunit.TraitAttribute("Description", "No filtering case. reload")]
        [Xunit.TraitAttribute("Category", "mainmodel")]
        public virtual void NoFilteringCase_Reload()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("No filtering case. reload", new string[] {
                        "mainmodel"});
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
 testRunner.Given("I have file \"test.log\" on disk", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 47
   testRunner.And("The file contains 2 messages with levels \"INFO\" and \"ERROR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.When("I press open with default filtering parameters", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 49
   testRunner.And("wait 6 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
   testRunner.And("I press reload", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
   testRunner.And("wait 6 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
 testRunner.Then("the number of shown messages should be 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Read last opened log on start")]
        [Xunit.TraitAttribute("FeatureTitle", "SpecOpenLogFile")]
        [Xunit.TraitAttribute("Description", "Read last opened log on start")]
        [Xunit.TraitAttribute("Category", "mainmodel")]
        public virtual void ReadLastOpenedLogOnStart()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Read last opened log on start", new string[] {
                        "mainmodel"});
#line 55
this.ScenarioSetup(scenarioInfo);
#line 56
 testRunner.Given("I have file \"test.log\" on disk", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 57
   testRunner.And("The file contains 2 messages with levels \"INFO\" and \"ERROR\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.When("I start application with default filtering parameters", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
   testRunner.And("wait 6 seconds", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.Then("the number of shown messages should be 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SpecOpenLogFileFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SpecOpenLogFileFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
