//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logviewer.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("logviewer.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling previous log loading in progress ....
        /// </summary>
        internal static string CancelPrevious {
            get {
                return ResourceManager.GetString("CancelPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating page to display in progress ....
        /// </summary>
        internal static string CreateRtfInProgress {
            get {
                return ResourceManager.GetString("CreateRtfInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string DaysGenitivePlural {
            get {
                return ResourceManager.GetString("DaysGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string DaysGenitiveSingular {
            get {
                return ResourceManager.GetString("DaysGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day.
        /// </summary>
        internal static string DaysNominative {
            get {
                return ResourceManager.GetString("DaysNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default template.
        /// </summary>
        internal static string DefaultParsingTemplateName {
            get {
                return ResourceManager.GetString("DefaultParsingTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding detection in progress ....
        /// </summary>
        internal static string EncodingDetectionInProgress {
            get {
                return ResourceManager.GetString("EncodingDetectionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log reading completed. Log will be displayed in about {0} seconds..
        /// </summary>
        internal static string FinishLoading {
            get {
                return ResourceManager.GetString("FinishLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string HoursGenitivePlural {
            get {
                return ResourceManager.GetString("HoursGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string HoursGenitiveSingular {
            get {
                return ResourceManager.GetString("HoursGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour.
        /// </summary>
        internal static string HoursNominative {
            get {
                return ResourceManager.GetString("HoursNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total: {1} To display: {8} Displayed: {0}   On the page T:{2}  D:{3}  I:{4}  W:{5}  E:{6}  F:{7}   .
        /// </summary>
        internal static string LogInfoFormatString {
            get {
                return ResourceManager.GetString("LogInfoFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min level must be less or equal then max level.
        /// </summary>
        internal static string MinLevelGreaterThenMax {
            get {
                return ResourceManager.GetString("MinLevelGreaterThenMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string MinutesGenitivePlural {
            get {
                return ResourceManager.GetString("MinutesGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string MinutesGenitiveSingular {
            get {
                return ResourceManager.GetString("MinutesGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to munute.
        /// </summary>
        internal static string MinutesNominative {
            get {
                return ResourceManager.GetString("MinutesNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template compilation in progress ....
        /// </summary>
        internal static string PatternCompilation {
            get {
                return ResourceManager.GetString("PatternCompilation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template compilation finished. Log reading in progress ....
        /// </summary>
        internal static string PatternCompilationFinished {
            get {
                return ResourceManager.GetString("PatternCompilationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read completed.  Taken {0}.
        /// </summary>
        internal static string ReadCompletedTemplate {
            get {
                return ResourceManager.GetString("ReadCompletedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less then second.
        /// </summary>
        internal static string RemainingLessThenSecond {
            get {
                return ResourceManager.GetString("RemainingLessThenSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string RemainingOnlySeconds {
            get {
                return ResourceManager.GetString("RemainingOnlySeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {4} {1} {5} {2} {6} {3} {7}.
        /// </summary>
        internal static string RemainingWithDays {
            get {
                return ResourceManager.GetString("RemainingWithDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {3} {1} {4} {2} {5}.
        /// </summary>
        internal static string RemainingWithHours {
            get {
                return ResourceManager.GetString("RemainingWithHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {2} {1} {3}.
        /// </summary>
        internal static string RemainingWithMinutes {
            get {
                return ResourceManager.GetString("RemainingWithMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string SecondsGenitivePlural {
            get {
                return ResourceManager.GetString("SecondsGenitivePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string SecondsGenitiveSingular {
            get {
                return ResourceManager.GetString("SecondsGenitiveSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string SecondsNominative {
            get {
                return ResourceManager.GetString("SecondsNominative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string SizeBytes {
            get {
                return ResourceManager.GetString("SizeBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eb.
        /// </summary>
        internal static string SizeEBytes {
            get {
                return ResourceManager.GetString("SizeEBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gb.
        /// </summary>
        internal static string SizeGBytes {
            get {
                return ResourceManager.GetString("SizeGBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kb.
        /// </summary>
        internal static string SizeKBytes {
            get {
                return ResourceManager.GetString("SizeKBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb.
        /// </summary>
        internal static string SizeMBytes {
            get {
                return ResourceManager.GetString("SizeMBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pb.
        /// </summary>
        internal static string SizePBytes {
            get {
                return ResourceManager.GetString("SizePBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tb.
        /// </summary>
        internal static string SizeTBytes {
            get {
                return ResourceManager.GetString("SizeTBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} %.
        /// </summary>
        internal static string SpeedPercent {
            get {
                return ResourceManager.GetString("SpeedPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} %  ({1}/second) remain {2}.
        /// </summary>
        internal static string SpeedPercentWithRemain {
            get {
                return ResourceManager.GetString("SpeedPercentWithRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file detected. File must be not empty to be displayed..
        /// </summary>
        internal static string ZeroFileDetected {
            get {
                return ResourceManager.GetString("ZeroFileDetected", resourceCulture);
            }
        }
    }
}
