//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace logviewer.core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("logviewer.core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling previous log loading in progress ....
        /// </summary>
        internal static string CancelPrevious {
            get {
                return ResourceManager.GetString("CancelPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating page to display in progress ....
        /// </summary>
        internal static string CreateRtfInProgress {
            get {
                return ResourceManager.GetString("CreateRtfInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding detection in progress ....
        /// </summary>
        internal static string EncodingDetectionInProgress {
            get {
                return ResourceManager.GetString("EncodingDetectionInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min level must be less or equal then max level.
        /// </summary>
        internal static string MinLevelGreaterThenMax {
            get {
                return ResourceManager.GetString("MinLevelGreaterThenMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string SizeBytes {
            get {
                return ResourceManager.GetString("SizeBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eb.
        /// </summary>
        internal static string SizeEBytes {
            get {
                return ResourceManager.GetString("SizeEBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gb.
        /// </summary>
        internal static string SizeGBytes {
            get {
                return ResourceManager.GetString("SizeGBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kb.
        /// </summary>
        internal static string SizeKBytes {
            get {
                return ResourceManager.GetString("SizeKBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb.
        /// </summary>
        internal static string SizeMBytes {
            get {
                return ResourceManager.GetString("SizeMBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pb.
        /// </summary>
        internal static string SizePBytes {
            get {
                return ResourceManager.GetString("SizePBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tb.
        /// </summary>
        internal static string SizeTBytes {
            get {
                return ResourceManager.GetString("SizeTBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file detected. File must be not empty to be displayed..
        /// </summary>
        internal static string ZeroFileDetected {
            get {
                return ResourceManager.GetString("ZeroFileDetected", resourceCulture);
            }
        }
    }
}
